#!/usr/bin/env bash

if [ $(gsettings get org.gnome.desktop.peripherals.touchpad send-events) == "'enabled'" ]; then
    echo "Switching off"
    gsettings set org.gnome.desktop.peripherals.touchpad send-events disabled
    evtest --grab /dev/input/event2
    gsettings set org.gnome.desktop.a11y.applications screen-keyboard-enabled true
    
    
else
    echo "Switching on"
    gsettings set org.gnome.desktop.peripherals.touchpad send-events enabled
    killall evtest
    gsettings set org.gnome.desktop.a11y.applications screen-keyboard-enabled false

fi
